### ISSUE TITLE
2: Add expense form

### ISSUE THREAD

**Issue by FNKMYR** [FNKMYR/capstone-project#1]
## Value proposition

**As a** user **I want to** see the add expense form on a new page **in order to** have a better overview and add more details.

## Description/Scribble:

<img width="142" alt="image" src="https://user-images.githubusercontent.com/97096534/157008539-1317a45f-ffdd-4e18-b7e0-985a6755a234.png">

## Acceptance criteria:

- [x] The main page footer is a button 'Add expense' that leads to the form page
- [x] The form has an input for title, comment, value and date
   - [x] The footer is the submit button
- [x] Submitting the form adds a new item to the expense list
- [x] The form page has a back button in the header which navigates back to the list without submitting

## Tasks
- [x] Add pages/ExpesesPage and pages/AddExpensePage
- [x] Add React Router
- [x] Edit components/ExpenseForm
   - [x] Add additional input fields
   - [x] Add back button
- [x] Make main page footer a button to open empty form
