### ISSUE TITLE
6: Balance page

### ISSUE THREAD

**Issue by FNKMYR** [FNKMYR/capstone-project#11]
## Value proposition

**As a** user **I want to** have an overview of each members expenses **in order to** distribute the expenses fairly.

## Description/Scribble:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/97096534/159226708-0c8378cb-3fa2-417b-a55e-48302b4e871a.png">

## Acceptance criteria:

- [ ] Expense page footer navigates between expenses & balances
- [ ] Balance page shows how much every member has spent and received
- [ ] Shows the balance ( € spent - € received ) for each member
   - [ ] If spent > received (balance >= 0), balance is green, otherwise red

## Tasks
- [ ] Add pages/BalancePage
  - [ ] Add route to page
- [ ] Write function do calculate spent, received & balance from expenses
- [ ] Add components/Balance
- [ ] Add components/Navigation
