### ISSUE TITLE
7: Add local storage

### ISSUE THREAD

**Issue by FNKMYR** [FNKMYR/capstone-project#15]
## Value proposition

**As a** user **I want to** reload the page without all inputs resetting **in order to** use the app over a longer period of time.

## Description/Scribble:

Local storage sync will be added through the useLocalStorage React Hook.

## Acceptance criteria:

- [ ] Entries remain present after a page reload

## Tasks
- [ ] Add hooks/useLocalStorage
- [ ] Sync all states with local storage
