### ISSUE TITLE
8: Pay up function

### ISSUE THREAD

**Issue by FNKMYR** [FNKMYR/capstone-project#16]
## Value proposition

**As a** user **I want to** have a 'pay up' button & page **in order to** set all balances to zero again.

## Description/Scribble:

![image](https://user-images.githubusercontent.com/97096534/160577299-580e3a28-fc8e-4da6-807a-ad6f3c9f3351.png)

## Acceptance criteria:

- [ ] "Pay up" button is on Balances page
- [ ] A new page is open which shows how much each member owes another member
- [ ] The function calculates the least amount of necessary transactions to bring all balances to zero.

## Tasks
- [ ] Add pages/PayUpPage
  - [ ] Add route to page
- [ ] Write function to calculate the transactions
- [ ] Add components/PayUpList
- [ ] Add components/PayUpItem
