### ISSUE TITLE
3: Add members to SplitPal

### ISSUE THREAD

**Issue by FNKMYR** [FNKMYR/capstone-project#2]
## Value proposition

**As a** user **I want to** add members to the SplitPal **in order to** track who has paid and received how much money.

## Description/Scribble:

<img width="148" alt="image" src="https://user-images.githubusercontent.com/97096534/157009212-8a51f992-8d8b-4bf0-a24f-f28f07343a30.png">

## Acceptance criteria:

- [ ] The 'subheader' (Total expense area) includes a text input field and submit button to add/edit members
  - [ ] Members can be input separated by commas
  - [ ] Every input overrides the previous list of members
  - [ ] The list of members can be seen above the input form
- [ ] The add expense form now includes following fields:
   - [ ] 'Paid by', a dropdown with the names of all members
   - [ ] 'Paid for', a checkbox list with the names of all members
- [ ] The expense list items also include the 'Paid by' and 'Paid for' information

## Tasks
- [ ] Add components/MembersForm
   - [ ] Storybook
   - [ ] Tests
- [ ] Edit components/ExpenseForm
- [ ] Edit components/ExpenseList
