### ISSUE TITLE
1: SplitPal expenses page

### ISSUE THREAD

**Issue by FNKMYR** [FNKMYR/capstone-project#4]
## Value proposition

**As a** user **I want to** add expenses **in order to** track them and see the total expenses.

## Description:

<img width="191" alt="image" src="https://user-images.githubusercontent.com/97096534/157436324-ba98d4f5-66ed-4333-bdc3-8857bb63c197.png">

## Acceptance criteria:

- [x] A form lets you add expenses with a title and a value
   - [x] Both fields are required
   - [x] Value field only accepts numeric input
- [x] Fixed header 'SplitPals'
- [x] Total expenses are shown
   - [x] is updated when new expenses are added
- [x] There is a list of expenses
   - [x] Shows title and value
   - [x] New expenses added through the form are added to the list
   - [x] Entries can be deleted through a 'DEL' button

## Tasks
- [x] Create components/Header
    - [x] Storybook
    - [x] Tests
- [x] Create components/ExpenseList
    - [x] Add calculated value for total expenses
    - [x] Storybook
    - [x] Tests
- [x] Add components/Expense
    - [x] Add delete button
    - [x] Tests
    - [x] Storybook
- [x] Create components/ExpenseForm
    - [x] Storybook
    - [x] Tests
- [x] Add minimal overall styling
