### ISSUE TITLE
Theme and styling

### ISSUE THREAD

**Issue by FNKMYR** [FNKMYR/capstone-project#8]
## Value proposition

**As a** user **I want to** see a consistently styled app **in order to** have a better user experience.

## Description/Scribble:

![image](https://user-images.githubusercontent.com/97096534/158783750-9093f15f-971e-4271-9e72-b0c7b0c7233f.png)

## Acceptance criteria:

- [ ] The colors are consistent
  - [ ] Blue header
  - [ ] Blue footer
  - [ ] Blue add button
- [ ] The text size, font and color are consistent

## Tasks
- [ ] Add a theme
- [ ] Edit all components according to that theme
- [ ] Replace button components with figma SVG exports
