### ISSUE TITLE
5: Add edit page

### ISSUE THREAD

**Issue by FNKMYR** [FNKMYR/capstone-project#9]
## Value proposition

**As a** user **I want to** open an edit page **in order to** edit expenses after I posted them.

## Description/Scribble:

<img width="184" alt="image" src="https://user-images.githubusercontent.com/97096534/158859163-2a834355-2d0e-4aab-b330-f21fd3cf8c28.png">

## Acceptance criteria:

- [ ] The edit page is opened by clicking on an expense list item
- [ ] The values of all form fields represent the corresponding expense data
- [ ] When submitting, the new input data overwrites the previous expense data

## Tasks
- [ ] Add pages/EditExpensePage
   - [ ] Include components/ExpenseForm
   - [ ] Adjust input/output data
